apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
        - name: backend
          image: rag-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: groq-api-key
            - name: GROQ_MODEL
              value: "llama-3.1-8b-instant"
            - name: LLM_BACKEND
              value: "groq"
            - name: EMBEDDINGS_BACKEND
              value: "hf"
            - name: EMBEDDINGS_MODEL
              value: "sentence-transformers/all-MiniLM-L6-v2"
            - name: CORS_ORIGINS_STR
              value: "https://your-frontend-domain.vercel.app"
